name: Repository Dispatch

on:
  repository_dispatch:
    types: [run]

jobs:
  hello_world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello
        run: |
          echo "Hellow world" 